services:
  app:
    build:
      context: .
    container_name: fitness-tracker-ui
    environment:
      NODE_ENV: development
      FITNESS_TRACKER_API_BASE_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
